### ISSUE TITLE
CK Pool connection error after update

### ISSUE THREAD

**Issue by cmyk** [jstefanop/apolloapi-v2#10]
After updating to 2.0.5 I get the following error message:
```
CK Pool Disconnected
Please check your node connection and the CK Pool status.
```
Also, the update dialogue got stuck. It never completed, albeit the content behind the update window refreshed.

**Comment by SearchAndDestroy** [comment]
I got the same message after switching to Solo Mining on my Apollo II. It came installed with 2.0.5.
Also does it support Segwit and Taproot addresses? I got address invalid with both types. I know solo,ckpool.org supports taproot addresses (bc1...), so why not on the Apollo II?

**Comment by jstefanop** [comment]
does a reboot fix this after the node is fully synced? This usually happens when your node is still syncing and ckpool has not started yet...need to catch this case and display the node is syncing

**Comment by jstefanop** [comment]
yes taproot is a limitation with ckpool, legacy and segwit should be fine for solo mining purposes. 

We are working on adding support for .workername in next update.
