### ISSUE TITLE
Question about my Apollo II mining stats

### ISSUE THREAD

**Issue by daviddahl** [jstefanop/apolloapi-v2#11]
I would like to pull stats from my Apollo II and visualize them in grafana on another machine on my network.

I see there is some stats collection here: https://github.com/jstefanop/apolloapi-v2/blob/main/src/store/api/miner/minerStats.js

is there any documentation on the best way to call an endpoint to get this data? Is graphQL accessible on the box?

**Comment by michelem09** [comment]
Hello,
you can query Apollo API via GraphQL using this endpoint http://<APOLLO-IP>:5000/api/graphql

To find out what to query you can look at this https://github.com/jstefanop/apolloui-v2/blob/main/src/graphql/miner.js

Sorry still no documentation for this but we could think about it.

**Comment by daviddahl** [comment]
That does not work via the local network, I get a 404...
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/f16300cf-b372-4e43-8922-1e435c57597b">
