### ISSUE TITLE
Node not connecting to the network 

### ISSUE THREAD

**Issue by Whodat78** [jstefanop/apolloapi-v2#21]
During the setup process of my Apollo 2 my node was connected and was uploading blocks and at around 50% upload just stopped and refused connection.  Now it says connection refused.  I reflashed the SD but still can't connect.  I am new to this and was really looking forward to running a node.  Hopefully I can get connected again a start running the node.  Any recommendations or guidance would be great.

**Comment by Whodat78** [comment]
Seems as though the new updated version is not working for me.  Keeps crashing @block 400,000 or so.  Just reflashed to the v2.0.5 update and Seems to be running smoothly now with no connection refused message.
 I'll post an update soon.

**Comment by Whodat78** [comment]
Still not working, node will not sync. Keeps crashing @ %50 download/sync

**Comment by michelem09** [comment]
Did you try to format the Node disk and start over?

**Comment by Whodat78** [comment]
Node can't fully sync, keeps crashing @ %50 sync. (Connection refused)

**Comment by Whodat78** [comment]
Yes, a few times.  Been trying for a week now but still the same results.  Reflashed SD and Reformat SSD a couple a few times now. But still the same results

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Whodat78** [comment]
Just picked up a new modem and router, 🤞
