### ISSUE TITLE
Unable to load image onto SD Card

### ISSUE THREAD

**Issue by mjohngreene** [jstefanop/apolloapi-v2#4]
I am having problems installing the MCU2 image.  First, when I go to https://www.dropbox.com/scl/fi/o27r4gp1ejxz38ilmdeu8/apollo-2-mcu2_110424.img.xz?rlkey=ey6bruzanptquug9i8lt2rt2t&e=5&dl=0 I get:

![Screenshot from 2024-05-05 11-34-31](https://github.com/jstefanop/apolloapi-v2/assets/24979484/44f95ec8-0351-457e-b33e-f6867b1452ac)

This seems odd for multiple reasons.

Second, when I download the image and attempt to install it via Etcher, I get:

![Screenshot from 2024-05-05 11-33-54](https://github.com/jstefanop/apolloapi-v2/assets/24979484/f26581e6-2bf5-4c9a-9adb-89a57032d6fb)

Note that it seems to run through the “flashing” part just fine but crashes at the very end of the “verification” step.

Last, if I try to install directly from the Dropbox URL instead of downloading it to my PC first and then installing I get:

![Screenshot from 2024-05-04 14-56-11](https://github.com/jstefanop/apolloapi-v2/assets/24979484/58c0185c-0674-4aa9-848d-0b00e2ed7d2e)

Any thoughts as to what might be going on?  Are other users able to install/upgrade their Node via instructions at https://www.futurebit.io/flashing-sd-card?

Thanks in advance.

**Comment by jstefanop** [comment]
Hi the warning is normal it's a large 2gig file. You need to download it from Dropbox and not load from url. 

Make sure you don't touch the file or decompress it, just select it in etcher after it downloads and select the sd card. 

You can double check the download is not corrupted by checking the sha256 checksum.

**Comment by wwong75** [comment]
Hi,

I'm having a different Etcher flashing problem with a diffreent checksum.   I checked the file checksum:

ww@Win286 Downloads % shasum -a 256 apollo-2-mcu2_110424.img.xz
6cc29f8df5756fea7e94aba901ca0a0dd2a4df637000c4f38f9f1df7ea037b65 apollo-2-mcu2_110424.img.xz
ww@Win286 Downloads %

SHA256 Checksum
6cc29f8df5756fea7e94aba901ca0a0dd2a4df637000c4f38f9f1df7ea037b65 apollo-2-mcu2_110424.img.xz

Etcher errors and says: "Source and destination checksums do not match: 435bdacfb6df9410 !== f780a791f2e86f25"

index.js:2 {size: 15931539456, isVirtual: false, enumerator: 'DiskArbitration', logicalBlockSize: 512, raw: '/dev/rdisk4', …}blockSize: 512busType: "USB"busVersion: nulldescription: "Generic MassStorageClass Media"device: "/dev/disk4"devicePath: "IODeviceTree:/arm-io@10F00000/apcie@90000000/pci-bridge1@1/pcie-xhci@0"displayName: "/dev/disk4"enumerator: "DiskArbitration"error: nullisCard: falseisReadOnly: falseisRemovable: trueisSCSI: falseisSystem: falseisUAS: nullisUSB: trueisVirtual: falselogicalBlockSize: 512mountpoints: []partitionTableType: "mbr"raw: "/dev/rdisk4"size: 15931539456[[Prototype]]: Object
index.js:2 {name: 'Error', message: 'Source and destination checksums do not match: 435bdacfb6df9410 !== f780a791f2e86f25', stack: 'Error: Source and destination checksums do not mat…jections (node:internal/process/task_queues:95:5)', code: 'EVALIDATION'}code: "EVALIDATION"message: "Source and destination checksums do not match: 435bdacfb6df9410 !== f780a791f2e86f25"name: "Error"stack: "Error: Source and destination checksums do not match: 435bdacfb6df9410 !== f780a791f2e86f25\n    at CountingHashStream.<anonymous> (/snapshot/Users/runner/work/etcher/etcher/node_modules/etcher-sdk/build/source-destination/source-destination.js:158:36)\n    at CountingHashStream.emit (node:events:518:28)\n    at CountingHashStream.<anonymous> (/snapshot/Users/runner/work/etcher/etcher/node_modules/etcher-sdk/build/source-destination/source-destination.js:78:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"[[Prototype]]: Object

I opened an issue with Etcher to troubleshoot.    Any ideas what could cause this type of checksum issue? 

Thanks

**Comment by jstefanop** [comment]
just released the 2.0.5 images in release section try those. FYI etcher has some sort of issue when imaging directly from .xz file, it will throw and error in the end but flash should be successful.

**Comment by wwong75** [comment]
After flashing to 2.0.5, Full Node does not boot.   Power on -> Fan 100% for over 1 minute  -> No signal to keyboard or HDMI 

I do not have Linux box.   I verified and flashed on both Windows 10 and macOS Sonoma using latest version of Etcher: 

ww@Win286 Downloads % shasum -a 256 apollo-2-mcu2_040624.img.xz
cd1bca4f6582a1b49edb47a4dd57138b57d05963c804ea506a52d0590ee0c14a  apollo-2-mcu2_040624.img.xz
ww@Win286 Downloads % 

C:\Users\tke\Downloads>certutil -hashfile apollo-2-mcu2_040624.img.xz sha256
SHA256 hash of apollo-2-mcu2_040624.img.xz:
cd1bca4f6582a1b49edb47a4dd57138b57d05963c804ea506a52d0590ee0c14a
CertUtil: -hashfile command completed successfully.

C:\Users\tke\Downloads>

- Both failed Etcher verification with same Source/Destination error: 
   Source and destination checksums do not match: bed6d47d45a3c91c !== f3eca05e8e299fa4 Windows 10
   Source and destination checksums do not match: bed6d47d45a3c91c !== f3eca05e8e299fa4 MacOS

If the above is not the issue as you mentioned and image was flashed correctly on the SD card, could this be a hw issue? I normally see my keyboard light up and a HDMI signal upon power on but I don't remember the sequence if the OS needs to load first to get signal to the keyboard and HDMI.   If there is no SD card in the slot, would there still be signal to the keyboard and HDMI when powering on?  
Thanks

**Comment by jstefanop** [comment]
It's a problem with etcher, you need to either decompress the image or use the last stable release here: 

https://github.com/balena-io/etcher/releases/tag/v1.18.11

**Comment by wwong75** [comment]
It worked using v1.18.11.  I should have tried a stable version before posting.   I'm in and will configure.   If there's anything I can do to help with time permitting, please let me know.  
Thank you

**Comment by auc0le** [comment]
Etcher would not give me a successful flash no matter what I did.  I ended up using the raspberry pi imager program to complete my upgrade process.  Good luck!

**Comment by jstefanop** [comment]
> It's a problem with etcher, you need to either decompress the image or use the last stable release here:
> 
> https://github.com/balena-io/etcher/releases/tag/v1.18.11

Please see above this is a problem with etcher on their recent releases, they pretty much broke the program for all platforms. 

Please use that version as it's stable and seems to work.
